version: "3"

volumes:
        wordpress:
                driver: local
                driver_opts:
                        device: /home/arbutnar/data/wordpress
                        o: bind
                        type: none
        mariadb:
                driver: local
                driver_opts:
                        device: /home/arbutnar/data/mariadb
                        o: bind
                        type: none

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./nginx/.
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - ./.env
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    restart: always

  mariadb:
    container_name: mariadb
    build: ./mariadb/.
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
    restart: always